# Generated by Django 6.0.2 on 2026-02-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, to="products.tag"),
        ),
    ]
